In [3]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score

import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("medical_insurance.csv")
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [7]:
df["sex"]

0       female
1         male
2         male
3         male
4         male
         ...  
1333      male
1334    female
1335    female
1336    female
1337    female
Name: sex, Length: 1338, dtype: object

In [8]:
df["sex"].replace({"female":0,'male':1},inplace=True)

In [9]:
no_sex_value={"female":0,'male':1}

In [10]:
df["smoker"].value_counts()

no     1064
yes     274
Name: smoker, dtype: int64

In [11]:
df["smoker"].replace({"no":0,'yes':1},inplace=True)

In [12]:
no_smoker_val={"no":0,'yes':1}

In [13]:
df["region"].value_counts().to_dict()

{'southeast': 364, 'southwest': 325, 'northwest': 325, 'northeast': 324}

In [14]:
df = pd.get_dummies(df,columns=["region"])
df

age  sex     bmi  children  smoker      charges  region_northeast  \
0      19    0  27.900         0       1  16884.92400                 0   
1      18    1  33.770         1       0   1725.55230                 0   
2      28    1  33.000         3       0   4449.46200                 0   
3      33    1  22.705         0       0  21984.47061                 0   
4      32    1  28.880         0       0   3866.85520                 0   
...   ...  ...     ...       ...     ...          ...               ...   
1333   50    1  30.970         3       0  10600.54830                 0   
1334   18    0  31.920         0       0   2205.98080                 1   
1335   18    0  36.850         0       0   1629.83350                 0   
1336   21    0  25.800         0       0   2007.94500                 0   
1337   61    0  29.070         0       1  29141.36030                 0   

      region_northwest  region_southeast  region_southwest  
0                    0                 0                 1  
1                    0                 1                 0  
2                    0                 1                 0  
3                    1                 0                 0  
4                    1                 0                 0  
...                ...               ...               ...  
1333                 1                 0                 0  
1334                 0                 0                 0  
1335                 0                 1                 0  
1336                 0                 0                 1  
1337                 1                 0                 0  

[1338 rows x 10 columns]

In [15]:
df["children"].value_counts()

0    574
1    324
2    240
3    157
4     25
5     18
Name: children, dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               1338 non-null   int64  
 1   sex               1338 non-null   int64  
 2   bmi               1338 non-null   float64
 3   children          1338 non-null   int64  
 4   smoker            1338 non-null   int64  
 5   charges           1338 non-null   float64
 6   region_northeast  1338 non-null   uint8  
 7   region_northwest  1338 non-null   uint8  
 8   region_southeast  1338 non-null   uint8  
 9   region_southwest  1338 non-null   uint8  
dtypes: float64(2), int64(4), uint8(4)
memory usage: 68.1 KB


# Train test split

In [17]:
x=df.drop(['charges'],axis=1)
y=df['charges']

In [18]:
x

age  sex     bmi  children  smoker  region_northeast  region_northwest  \
0      19    0  27.900         0       1                 0                 0   
1      18    1  33.770         1       0                 0                 0   
2      28    1  33.000         3       0                 0                 0   
3      33    1  22.705         0       0                 0                 1   
4      32    1  28.880         0       0                 0                 1   
...   ...  ...     ...       ...     ...               ...               ...   
1333   50    1  30.970         3       0                 0                 1   
1334   18    0  31.920         0       0                 1                 0   
1335   18    0  36.850         0       0                 0                 0   
1336   21    0  25.800         0       0                 0                 0   
1337   61    0  29.070         0       1                 0                 1   

      region_southeast  region_southwest  
0                    0                 1  
1                    1                 0  
2                    1                 0  
3                    0                 0  
4                    0                 0  
...                ...               ...  
1333                 0                 0  
1334                 0                 0  
1335                 1                 0  
1336                 0                 1  
1337                 0                 0  

[1338 rows x 9 columns]

In [19]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=25)

In [21]:
y_train


629     42983.458500
556      8334.589600
427      7323.734819
1047    44501.398200
98      22412.648500
            ...     
886     27218.437250
143     18157.876000
474     25382.297000
318      7421.194550
1156    39722.746200
Name: charges, Length: 1070, dtype: float64

In [22]:
y_test

748     8556.90700
633     7173.35995
651    10579.71100
411    19594.80965
502    22218.11490
          ...     
332    13429.03540
893    44202.65360
822     1621.88270
645    10141.13620
921    13462.52000
Name: charges, Length: 268, dtype: float64

In [23]:
x_test

age  sex     bmi  children  smoker  region_northeast  region_northwest  \
748   47    0  36.000         1       0                 0                 0   
633   40    1  22.705         2       0                 1                 0   
651   53    0  39.600         1       0                 0                 0   
411   44    0  20.235         1       1                 1                 0   
502   51    1  23.210         1       1                 0                 0   
..   ...  ...     ...       ...     ...               ...               ...   
332   61    0  31.160         0       0                 0                 1   
893   47    1  38.940         2       1                 0                 0   
822   18    0  31.130         0       0                 0                 0   
645   48    1  30.780         3       0                 1                 0   
921   62    0  33.200         0       0                 0                 0   

     region_southeast  region_southwest  
748                 0                 1  
633                 0                 0  
651                 1                 0  
411                 0                 0  
502                 1                 0  
..                ...               ...  
332                 0                 0  
893                 1                 0  
822                 1                 0  
645                 0                 0  
921                 0                 1  

[268 rows x 9 columns]

In [24]:
x_train

age  sex     bmi  children  smoker  region_northeast  region_northwest  \
629    44    0  38.950         0       1                 0                 1   
556    46    1  33.440         1       0                 1                 0   
427    18    0  29.165         0       0                 1                 0   
1047   22    1  52.580         1       1                 0                 0   
98     56    1  19.950         0       1                 1                 0   
...   ...  ...     ...       ...     ...               ...               ...   
886    57    1  28.975         0       1                 1                 0   
143    29    1  29.735         2       0                 0                 1   
474    54    1  25.100         3       1                 0                 0   
318    44    0  27.645         0       0                 0                 1   
1156   19    1  44.880         0       1                 0                 0   

      region_southeast  region_southwest  
629                  0                 0  
556                  0                 0  
427                  0                 0  
1047                 1                 0  
98                   0                 0  
...                ...               ...  
886                  0                 0  
143                  0                 0  
474                  0                 1  
318                  0                 0  
1156                 1                 0  

[1070 rows x 9 columns]

# Model Training

In [25]:
linear_model=LinearRegression()
linear_model.fit(x_train,y_train)

LinearRegression()

In [26]:
linear_model.intercept_

-12810.836224621784

# Testing Data evalation:

In [27]:
y_test_predict=linear_model.predict(x_test)

mse=mean_squared_error(y_test,y_test_predict)
rmse=np.sqrt(mse)
mae=mean_absolute_error(y_test,y_test_predict)
r2score=r2_score(y_test,y_test_predict)

print(mse,rmse,mae,r2score)

34633295.9297812 5885.006026316472 4283.190084376348 0.7547037664450407


# Training Data evalation:

In [28]:
y_train_predict=linear_model.predict(x_train)

mse=mean_squared_error(y_train,y_train_predict)
rmse=np.sqrt(mse)
mae=mean_absolute_error(y_train,y_train_predict)
r2score=r2_score(y_train,y_train_predict)

print(mse,rmse,mae,r2score)
   

37103631.535598874 6091.27503365255 4193.745575505876 0.7490732999835242


# Testing on Single row

In [ ]:
here we wan to check how our model work for new test data

we are checking through single record /row 

In [29]:
linear_model.n_features_in_

9

In [57]:
column=x.columns

### data  to check output for single row

In [31]:
x.head(1).T    # to get data column easily

0
age               19.0
sex                0.0
bmi               27.9
children           0.0
smoker             1.0
region_northeast   0.0
region_northwest   0.0
region_southeast   0.0
region_southwest   1.0

In [54]:

# for this data need to check charge value


age = 19
sex ='male'
bmi=27.9
children = 1
smoker='yes'
region='southwest'

### create array of input data


In [39]:
test_array = np.zeros(len(x.columns))
test_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

### assign value of input into this test array


In [55]:
test_array[0]=age
# test_array[1]=sex
test_array[2]=bmi
test_array[3]=children
# test_array[4]=smoker
# test_array[5]=region


In [44]:
test_array

array([19. ,  0. , 27.9,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ])

In [ ]:
# if we analyse above data .....
# sex and smoker column are in object ....we want int for easy calculation
# as well as we neeed to think about region column too having multiple values

### handling smoker and sex column

In [46]:
# create dictionary for column in wich value are replace 

label_data_dict={
    "sex":{"female":0,'male':1},
    "smoker":{"no":0,'yes':1}
}

In [47]:
label_data_dict

{'sex': {'female': 0, 'male': 1}, 'smoker': {'no': 0, 'yes': 1}}

In [48]:
# now for assigning value to test array use this dict

#test_array[1]=sex...sex ='male'

# test_array[1]=label_data_dict["sex"][male]    -----hardcoded

test_array[1]=label_data_dict["sex"][sex]


#test_array[4]=smoker-----smoker=yes

test_array[4]=label_data_dict["smoker"][smoker]



In [49]:
# updated test array with value of sex and smoker

test_array

array([19. ,  1. , 27.9,  1. ,  1. ,  0. ,  0. ,  0. ,  0. ])

### how to handle region

In [56]:
# test_array[5]=region

# our table has column like region_southwest....so

region='region_'+region
region

'region_southwest'

In [60]:
# find index value for region southwest in table

region_index=np.where(column==region)[0][0]
region_index

8

In [61]:
# at index set value as 1
test_array[region_index]=1

### final input test array

In [62]:
test_array

array([19. ,  1. , 27.9,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ])

### predict the output

In [65]:
charges=linear_model.predict([test_array])
charges

C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([26013.32881294])

In [66]:
charges=linear_model.predict([test_array])[0]
charges

C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


26013.328812937256

In [67]:
charges=np.around(linear_model.predict([test_array])[0],2)
charges

C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


26013.33

### create model/pickle file

In [ ]:
import pickle

with open(linear_model.pkl) as f:
    pickle.dump(linear_model,f)

### create json file

In [70]:
project_data={
      "sex":{"female":0,'male':1},
    "smoker":{"no":0,'yes':1},
    "column":list(x.columns)
}

In [71]:
project_data

{'sex': {'female': 0, 'male': 1},
 'smoker': {'no': 0, 'yes': 1},
 'column': ['age',
  'sex',
  'bmi',
  'children',
  'smoker',
  'region_northeast',
  'region_northwest',
  'region_southeast',
  'region_southwest']}

In [73]:
import json

with open('project_data.json','w') as f:
    json.dump(project_data,f)